### ISSUE TITLE
Exception on running without arguments

### ISSUE THREAD

**Issue by ligurio** [hwayne/tlacli#10]
```
sergeyb@pony:~/sources/MRG/packpack$ ~/.local/bin/tlacli 
Traceback (most recent call last):
  File "/home/sergeyb/.local/bin/tlacli", line 8, in <module>
    sys.exit(main())
  File "/home/sergeyb/.local/lib/python3.8/site-packages/tlacli/tlacli.py", line 16, in main
    args.run(args)
AttributeError: 'Namespace' object has no attribute 'run'
sergeyb@pony:~/sources/MRG/packpack$ 
```

Version: `tlacli-0.0.1`

**Comment by hwayne** [comment]
Could you share with me the src of `bin/tlacli`? I'm on Windows so don't know what it's compiled to.

**Comment by ligurio** [comment]
Sure.

```python
#!/usr/bin/python3
# -*- coding: utf-8 -*-
import re
import sys
from tlacli.tlacli import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```
